 
i am applying for financial aid because i'm unable to pay for any course, I'm belongs from a lower class family and i have no money to buy courses. What ever I'm studying  that is all from google. but google's content is not enough for going on appropriate path .so that's why i'm choosing coursera. Because this online platform has complete solution for study.  but Due to money i'm unable to buy the courses.
my education is going from bank education loan. i'm unable to buy courses and learn in coaching class.
I'm actively learning things from coursera past 6-7 month. and I'm doing well in the field of technology.
i recently crossed introduction of python and introduction to data science. So , I'm unable to buy  courses but i want to learn new things and active things. Hope this course will provide to me for grow my skills and learn new things.





I pursing Btech from Greater Noida Institute of Technology in computer science and engineering . AS im the student of Computer science it a need . but from the different aspect, i want to  ,learn new things and thing which will used in future. I want to be a Data Scientist and this course will help to be a data scientist.I am already studying things from google. but google has a limit . and i think im crossing that limit . but going to a actual path i need a teacher who is help to go in a right path. but i have no money to give to teachers and coaching institute.I'm actively learning things from coursera past 6-7 month. and I'm doing well in the field of technology.
i recently crossed introduction of python and introduction to data science. So , I'm unable to buy  courses but i want to learn new things and active things. Hope this course will provide to me for grow my skills and learn new things.
